[dependencies]
flate2 = "1"
home = "0.5"
serde_json = "1"
tar = "0.4"

[dependencies.clap]
features = ["derive", "unicode"]
version = "4"

[dependencies.reqwest]
default-features = false
features = ["charset", "http2", "rustls"]
version = "0.13"

[dependencies.serde]
features = ["serde_derive"]
version = "1"

[dependencies.tokio]
features = ["full"]
version = "1"

[package]
authors = ["Sora Tonami <ms0503@outlook.com>"]
edition = "2024"
name = "skel"
resolver = "3"
version = "0.2.1"
