[dependencies]
chrono = "0.4"
scraper = "0.25"

[dependencies.reqwest]
default-features = false
features = ["charset", "http2", "rustls"]
version = "0.13"

[dependencies.tokio]
features = ["full"]
version = "1"

[package]
authors = ["Sora Tonami <ms0503@outlook.com>"]
edition = "2024"
name = "swww-bing"
resolver = "3"
version = "0.2.0"
