[dependencies]
serde = { features = ["derive"], version = "1" }
serde_json = "1"
tokio = { features = ["full"], version = "1" }

[dependencies.reqwest]
default-features = false
features = ["charset", "http2", "json", "rustls"]
version = "0.13"

[package]
authors = ["Sora Tonami <ms0503@outlook.com>"]
edition = "2024"
name = "getemoji"
resolver = "3"
version = "0.2.0"
